name = "JessamineSymbolics"
uuid = "d293f0e1-bc3b-41ab-aeda-c552fb2511c4"
version = "0.3.0"
authors = ["W. Garrett Mitchener <garrett.mitchener@gmail.com> and contributors"]

[workspace]
projects = ["test"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Jessamine = "2807b6de-c4a7-4d42-9dc5-a90bb38e3ffd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
Distributions = "0.25.123"
Jessamine = "0.3.0"
LinearAlgebra = "1.12.0"
Random = "1.11.0"
RuntimeGeneratedFunctions = "0.5.17"
SymbolicUtils = "4.25.1"
Symbolics = "7.19.0"
TermInterface = "2.0.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[sources]
# Jessamine = {url = "https://github.com/wgm-applied-math/Jessamine.jl.git", rev = "v0.3.0"}
