# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        Documentation for JessamineSymbolics.jl
repo_url:         https://github.com/wgm-applied-math/JessamineSymbolics.jl
site_description: A symbolic regression package - interface to Symbolics.jl
site_author:      W. Garrett Mitchener

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
