# -*- yaml -*-
name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags:
      - 'v*' # supposedly this triggers the versioned / stable documentation branches

  # Allow me to run it manually
  workflow_dispatch:

  # Run when a release is published
  release:
    types: [published]

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      # - name: Setup Python
      #   uses: actions/setup-python@v7
      #   with:
      #     python-version: '3.14'
      #     cache: 'pip'
      # - name: Pip
      #   run: pip install -r requirements.txt
      - name: Setup Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1.12'
      - name: Julia cache
        uses: julia-actions/cache@v3
      - name: Install dependencies
        # This is complicated because Jessamine is posted on GitHub.
        # Apparently you have to develop() it, which can't be done
        # through Project.toml.
        run: julia --project=docs/ docs/setup.jl
      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
